export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_CHECKOUT_REQUEST = "USER_CHECKOUT_REQUEST";
export const USER_CHECKOUT_SUCCESS = "USER_CHECKOUT_SUCCESS";
export const USER_CHECKOUT_FAIL = "USER_CHECKOUT_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";
